tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/test.crt
        keyFile: /certs/test.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
      clientAuth:
        caFiles:
          - /certs/myCA.pem
        clientAuthType: RequireAndVerifyClientCert